[package]
name = "humoreic"
version = "0.1.0"
authors = ["Eduardo Espadeiro <eduardo.espadeiro@tecnico.ulisboa.pt>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serenity = "0.10.4"
